nelmio_cors:
    defaults:
        allow_origin: ['*']
        allow_headers: ['Content-Type']
        allow_methods: ['GET', POST, PUT, DELETE, OPTIONS']
        max_age: 3600
    paths:
        '^/':
            allow_origin: ['*']
            allow_headers: ['Content-Type']
            allow_methods: ['GET', POST, PUT, DELETE, OPTIONS']
            max_age: 3600
