services:
  # Service pour l'API Symfony
  app:
    build: .
    container_name: backend
    ports:
      - "8080:80"  # Redirige le port externe 8080 vers le port interne 80 du conteneur
    volumes:
      - .:/var/www/html
    networks:
      - app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql://root:root@db/rutix_db
    #command: php bin/console doctrine:migrations:generate --no-interaction && php bin/console doctrine:migrations:migrate --no-interaction  # Assure que Symfony écoute sur 0.0.0.0 et le port 80


  # Service pour la base de données MySQL
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rutix_db
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
    ports:
      - "3306:3306"
    networks:
      - app
    volumes:
      - db_data:/var/lib/mysql
   

volumes:
  db_data:
networks:
 app: